apiVersion: v1
kind: Service
metadata:
  name: { { .Release.Name } }-service
  labels:
    env: ENV_NAME
    owner: AUTHOR_NAME
spec:
  selector:
    project: { { .Release.Name } }  # Выбор подов с этим лейблом
  ports:
    - name: { { .Release.Name } }-listener
      protocol: PROTOCOL
      port: PORT_NUM  # Порт на Load Balancer
      targetPort: PORT_NUM  # Порт на подах
  type: SERVICE_TYPE